name: Run Unit Tests

on: 
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop
  release:
    types:
      - created

jobs:
  "unittest_reveng_paj7620":
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v2
       - uses: ruby/setup-ruby@v1
         with:
           ruby-version: 2.6
       - uses: actions/setup-python@v2
         with:
           python-version: '3.x'
       - name: Install Python Serial
         run: |
           python -m pip install --upgrade pip
           pip install pyserial
       - name: Run unit tests
         run: |
           g++ -v
           bundle install
           bundle exec arduino_ci.rb
         shell: bash
