name: Run Unit Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - created

jobs:
  "unittest_reveng_paj7620":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python Serial
        run: |
          python -m pip install --upgrade pip
          pip install pyserial
      - name: Run unit tests
        run: |
          g++ -v
          bundle install
          bundle exec arduino_ci.rb
        shell: bash
