name: Tools Checks

on:
  push:
    paths:
      - 'scripts/**'
    branches:
      - main
      - master
      - develop
  pull_request:
    paths:
      - 'scripts/**'
    branches:
      - main
      - master
      - develop

jobs:
  "lint_tools":
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v2
         with:
           python-version: '3.x'
       - name: Setup Virtual Environment
         run: |
           pip3 install virtualenv
           cd scripts
           ./create-virtualenv.sh
       - name: Run flake8
         if: always()
         run: |
           cd scripts
           source .paj7620-env/bin/activate
           flake8 --config=lint.ini
       - name: Run pylint
         if: always()
         run: |
           cd scripts
           source .paj7620-env/bin/activate
           pylint --rcfile=lint.ini ./*
